### __PROVA 3__

In [11]:
import numpy as np
from scipy import sparse
from scipy.sparse import csr_matrix

In [12]:
# DECLARANDO AS VARIAVEIS

row = np.array([0, 0, 1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4])
col = np.array([0, 1, 0, 1, 2, 1, 2, 3, 2, 3, 4, 3, 4])
data = np.array([4, -2, 4, -7, 3, 5, -11, 6, 2, -10, 8, 4, -8])

In [13]:
A = sparse.csr_matrix((data, (row, col)), shape=(5,5), dtype=float).toarray()
A

array([[  4.,  -2.,   0.,   0.,   0.],
       [  4.,  -7.,   3.,   0.,   0.],
       [  0.,   5., -11.,   6.,   0.],
       [  0.,   0.,   2., -10.,   8.],
       [  0.,   0.,   0.,   4.,  -8.]])

In [14]:
# CALCULANDO A INVERSA DA MATRIZ

A_inv = np.linalg.inv(A)

In [15]:
# DECLARANDO OS VALORES DO VETOR B

b1, b2, b3, b4, b5 = 30, 0, 0, 0, 80

b = np.array([b1, b2, b3, b4, b5])
print(b)

[30  0  0  0 80]


In [16]:
# CALCULO DAS ICOGNITAS

x = A_inv.dot(b)
x

array([  8.        ,   1.        ,  -8.33333333, -16.11111111,
       -18.05555556])

In [17]:
c1 = x[0]
c2 = x[1]
c3 = x[2]
c4 = x[3]
c5 = x[4]

In [18]:
def line():
    print("-"*45)

line()
print( 'RESULTADOS DAS CONCENTRAÇÕES' )
line()
print("O valor da concentração c1 é: {:.2f}".format(c1), "mg/m3")
print("O valor da concentração c2 é: {:.2f}".format(c2), "mg/m3")
print("O valor da concentração c3 é: {:.2f}".format(c3), "mg/m3")
print("O valor da concentração c4 é: {:.2f}".format(c4), "mg/m3")
print("O valor da concentração c5 é: {:.2f}".format(c5), "mg/m3")
line()

---------------------------------------------
RESULTADOS DAS CONCENTRAÇÕES
---------------------------------------------
O valor da concentração c1 é: 8.00 mg/m3
O valor da concentração c2 é: 1.00 mg/m3
O valor da concentração c3 é: -8.33 mg/m3
O valor da concentração c4 é: -16.11 mg/m3
O valor da concentração c5 é: -18.06 mg/m3
---------------------------------------------


CONFERINDO OS RESULTADOS

In [19]:
z1 = 4*c1-2*c2
z5 = 4*c4 - 8*c5

In [20]:
line()
print( 'CONFERINDO OS RESULTADOS DAS CONCENTRAÇÕES' )
line()
print(f"O resultado de b1={b1} e z1 = {z1:.2f}", "mg/m3")
print(f"O resultado de b5={b5} e z3 = {z5:.2f}", "mg/m3")
line()

---------------------------------------------
CONFERINDO OS RESULTADOS DAS CONCENTRAÇÕES
---------------------------------------------
O resultado de b1=30 e z1 = 30.00 mg/m3
O resultado de b5=80 e z3 = 80.00 mg/m3
---------------------------------------------
