## UNIVERSIDADE ESTADUAL DE SANTA CRUZ - UESC
#### DEPARTAMENTO DE ENGENHARIAS E COMPUTAÇÃO - DEC
#### CURSO DE ENGENHARIA QUÍMICA

**CET 1012** Modelagem, Simulação e Otimização de Processos Químicos.

**Professor**: Prof. Dr E.R.Edwards

**Tema:** Métodos Matriciais em Cálculos de Engenharia.

**Assunto**: Cálculo da inversa, $A^{-1}$ de uma matriz $4x4$.


Suponha uma matriz $A\vec{x}=\vec{b}$ de forma que o vetor $\vec{x}$ seja a incógnita que precisamos determinar, sendo:

$$ \vec{x} = \frac{b}{A} =A^{-1}.b .. Eq(\ 2 ) $$ 

Agora vamos pensar em como resolver um problema em que a matriz $A$ é da forma $4x4$ como mostrado abaixo:

\begin{equation}
	A = 
	\begin{bmatrix}
		a_{11} & a_{12}  & a_{13} & a_{14} \\
		a_{21} & a_{22}  & a_{23} & a_{24} \\
		a_{31} & a_{32}  & a_{33} & a_{34} \\
		a_{41} & a_{42}  & a_{43} & a_{44} \nonumber \\ 
	\end{bmatrix} 
\end{equation}

Para o cálculo das incógnitas, precisamos calcular $A^{-1}$ aplicando a seguinte expressão:

$$A^{-1} = \frac{1}{det(A)}.A^T ...Eq(\ 2 \ )$$ 

Sendo:

$det(A)$... O determinante da matriz A Eq( 3  )

$A^T$... a matriz transposta. Eq( 4 )

A matriz Transposta $A^T$ é calculada a partir da matriz Cofator ($A_c$) dada por:

$$ A_c = (-1)^{(i+j)} [a_{ij}] ... Eq(5)$$ 

Dessa forma, conseguimos obter a **Matriz cofator** na  Eq(5), fazer a **Matriz Transposta** na Eq(4) e juntamente com o **Determinante** na Eq(3) encontrar a **Matriz Inversa** ($A^{-1}$) na Eq(2) e obter as incógnitas $\vec{x}$ na Eq(1).


#### Aplicação:

Dada a matriz $A$, encontre sua inversa, $A^{-1}$ aplicando o método descrito acima.

\begin{equation}
A =
	\begin{bmatrix}
		 1 & 2   & 0 & 1 \\
		-1 & -3  & 0 & 1 \\
	     3 & 6   & 1 & 3 \\
		 2 & 4   & 0 & 3 \nonumber \\ 
	\end{bmatrix} 
\end{equation}


In [4]:
# declarar variaveis da matriz 4x4
a11, a12, a13, a14 = 1, 2, 0, 1
a21, a22, a23, a24 = -1, -3, 0, 1
a31, a32, a33, a34 = 3, 6, 1, 3
a41, a42, a43, a44 = 2, 4, 0, 3


#### Cálculo das Matrizes cofatores - Ac

Vamos fazer o mesmo para as outras células e seguir os passos da resolução anterior.

Calculo da célula a11
\begin{equation}
	c_{11} = (-1)^{(1+1)}.
	\begin{bmatrix}
		a_{22} & a_{23}  & a_{24}  \\
		a_{32} & a_{33}  & a_{34}  \\
		a_{42} & a_{43}  & a_{44}  \nonumber \\ 
	\end{bmatrix} 
\end{equation}


In [5]:
# CALCULANDO DA MATRIZ 2X2 DO ELEMENTO a11
# PARA CALCULAR REDUZ A MATRIZ 3X3 PARA UMA MATRIZ 2X2, NESSE CASO ISOLA O ELEMENTO a22.

# INDICE DO ELEMENTO A11
i = 1
j = 1

matriz11 = a22*((a33*a44)-(a34*a43)) - a23*((a32*a44)-(a34*a42)) + a24*((a32*a43)-(a33*a42))

c11 = (-1)**(i+j)*matriz11
matriz11

-13

Calculo da célula a12
\begin{equation}
	c_{12} = (-1)^{(1+2)}.
	\begin{bmatrix}
		a_{21} & a_{23}  & a_{24}  \\
		a_{31} & a_{33}  & a_{34}  \\
		a_{41} & a_{43}  & a_{44}  \nonumber \\ 
	\end{bmatrix} 
\end{equation}


In [6]:
i = 1
j = 2

matriz12 = a21*((a33*a44)-(a34*a43)) - a23*((a31*a44)-(a34*a41)) +  a24*((a31*a43)-(a33*a41))

c12 = (-1)**(i+j)*matriz12
c12

5

Calculo da célula a13
\begin{equation}
	c_{13} = (-1)^{(1+3)}.
	\begin{bmatrix}
		a_{21} & a_{22}  & a_{24}  \\
		a_{31} & a_{32}  & a_{34}  \\
		a_{41} & a_{42}  & a_{44}  \nonumber \\ 
	\end{bmatrix} 
\end{equation}


In [7]:
i = 1
j = 3

matriz13 = a21*((a32*a44)-(a34*a42)) - a22*((a31*a44)-(a34*a41)) + a24*((a31*a42)-(a32*a41))

c13 = (-1)**(i+j)*matriz13  
c13

3

Cálculo da célula a14.
\begin{equation}
	c_{14} = (-1)^{(1+4)}.
	\begin{bmatrix}
		a_{21} & a_{22}  & a_{23}  \\
		a_{31} & a_{32}  & a_{33}  \\
		a_{41} & a_{42}  & a_{43}  \nonumber \\ 
	\end{bmatrix} 
\end{equation}


In [8]:
i = 1
j = 4

matriz14 = a21*((a32*a43)-(a33*a42)) - a22*((a31*a43)-(a33*a41)) + a23*((a31*a42)-(a32*a41))

c14 = (-1)**(i+j)*matriz14
c14

2

Cálculo da célula a21.
\begin{equation}
	c_{21} = (-1)^{(2+1)}.
	\begin{bmatrix}
		a_{12} & a_{13}  & a_{14}  \\
		a_{32} & a_{33}  & a_{34}  \\
		a_{42} & a_{43}  & a_{44}  \nonumber \\ 
	\end{bmatrix} 
\end{equation}


In [9]:
i = 2
j = 1

matriz21 = a12*((a33*a44)-(a34*a43)) - a13*((a32*a44)-(a34*a42)) + a14*((a32*a43)-(a33*a42))

c21 = (-1)**(i+j)*matriz21
c21

-2

Cálculo da célula a22.
\begin{equation}
	c_{22} = (-1)^{(2+2)}.
	\begin{bmatrix}
		a_{11} & a_{13}  & a_{14}  \\
		a_{31} & a_{33}  & a_{34}  \\
		a_{41} & a_{43}  & a_{44}  \nonumber \\ 
	\end{bmatrix} 
\end{equation}


In [10]:
i = 2
j = 2

matriz22 = a11*((a33*a44)-(a34*a43)) - a13*((a31*a44)-(a34*a41)) + a14*((a31*a43)-(a33*a41))

c22 = (-1)**(i+j)*matriz22  
c22

1

Cálculo da célula a23.
\begin{equation}
c_{23} = (-1)^{(2+3)}.
	\begin{bmatrix}
		a_{11} & a_{12}  & a_{14}  \\
		a_{31} & a_{32}  & a_{34}  \\
		a_{41} & a_{42}  & a_{44}  \nonumber \\ 
	\end{bmatrix} 
\end{equation}


In [11]:
i = 2
j = 3

matriz23 = a11*((a32*a44)-(a34*a42)) - a12*((a31*a44)-(a34*a41)) + a14*((a31*a42)-(a32*a41))

c23 = (-1)**(i+j)*matriz23  
c23

0

Cálculo da célula a24.
\begin{equation}
c_{24} = (-1)^{(2+4)}.
	\begin{bmatrix}
		a_{11} & a_{12}  & a_{13}  \\
		a_{31} & a_{32}  & a_{33}  \\
		a_{41} & a_{42}  & a_{44}  \nonumber \\ 
	\end{bmatrix} 
\end{equation}


In [12]:
i = 2
j = 4

matriz24 = a11*((a32*a44)-(a33*a42)) - a12*((a31*a44)-(a33*a41)) + a13*((a31*a42)-(a32*a41))

c24 = (-1)**(i+j)*matriz24  
c24

0

Cálculo da célula a31.
\begin{equation}
c_{31} = (-1)^{(3+1)}.
	\begin{bmatrix}
		a_{12} & a_{13}  & a_{14}  \\
		a_{22} & a_{23}  & a_{24}  \\
		a_{42} & a_{43}  & a_{44}  \nonumber \\ 
	\end{bmatrix} 
\end{equation}


In [13]:
i = 3
j = 1

matriz31 = a12*((a23*a44)-(a24*a43)) - a13*((a22*a44)-(a24*a42)) + a14*((a22*a43)-(a23*a42))

c31 = (-1)**(i+j)*matriz31  
c31

0

Cálculo da célula a32.
\begin{equation}
c_{32} = (-1)^{(3+2)}.
	\begin{bmatrix}
		a_{11} & a_{13}  & a_{14}  \\
		a_{21} & a_{23}  & a_{24}  \\
		a_{41} & a_{43}  & a_{44}  \nonumber \\ 
	\end{bmatrix} 
\end{equation}


In [14]:
i = 3
j = 2

matriz32 = a11*((a23*a44)-(a24*a43)) - a13*((a21*a44)-(a24*a41)) + a14*((a21*a43)-(a23*a41))

c32 = (-1)**(i+j)*matriz32
c32

0

Cálculo da célula a33.
\begin{equation}
c_{33} = (-1)^{(3+3)}.
	\begin{bmatrix}
		a_{11} & a_{12}  & a_{14}  \\
		a_{21} & a_{22}  & a_{24}  \\
		a_{41} & a_{42}  & a_{44}  \nonumber \\ 
	\end{bmatrix} 
\end{equation}


In [15]:
i = 3
j = 3

matriz33 = a11*((a22*a44)-(a24*a42)) - a12*((a21*a44)-(a24*a41)) + a14*((a21*a42)-(a22*a41))

c33 = (-1)**(i+j)*matriz33
c33

-1

Cálculo da célula a34.
\begin{equation}
c_{34} = (-1)^{(3+4)}.
	\begin{bmatrix}
		a_{11} & a_{12}  & a_{13}  \\
		a_{21} & a_{22}  & a_{23}  \\
		a_{41} & a_{42}  & a_{43}  \nonumber \\ 
	\end{bmatrix} 
\end{equation}


In [16]:
i = 3
j = 4

matriz34 = a11*((a22*a43)-(a23*a42)) - a12*((a21*a43)-(a23*a41)) + a13*((a21*a42)-(a22*a41))

c34 = (-1)**(i+j)*matriz34
c34

0

Cálculo de célula a41.
\begin{equation}
c_{41} = (-1)^{(4+1)}.
	\begin{bmatrix}
		a_{12} & a_{13}  & a_{14}  \\
		a_{22} & a_{23}  & a_{24}  \\
		a_{32} & a_{33}  & a_{34}  \nonumber \\ 
	\end{bmatrix} 
\end{equation}


In [17]:
i = 4
j = 1

matriz41 = a12*((a23*a34)-(a24*a33)) - a13*((a22*a34)-(a24*a32)) + a14*((a22*a33)-(a23*a32))

c41 = (-1)**(i+j)*matriz41
c41

5

Cálculo da célula a42.
\begin{equation}
c_{42} = (-1)^{(4+2)}.
	\begin{bmatrix}
		a_{11} & a_{13}  & a_{14}  \\
		a_{21} & a_{23}  & a_{24}  \\
		a_{31} & a_{33}  & a_{34}  \nonumber \\ 
	\end{bmatrix}
\end{equation}


In [18]:
i = 4
j = 2

matriz42 = a11*((a23*a34)-(a24*a33)) - a13*((a21*a34)-(a24*a31)) + a14*((a21*a33)-(a23*a31))

c42 = (-1)**(i+j)*matriz42
c42

-2

Cálculo da célula a43.
\begin{equation}
c_{43} = (-1)^{(4+3)}.
	\begin{bmatrix}
		a_{11} & a_{12}  & a_{14}  \\
		a_{21} & a_{22}  & a_{24}  \\
		a_{31} & a_{32}  & a_{34}  \nonumber \\ 
	\end{bmatrix}
\end{equation}


In [19]:
i = 4
j = 3

matriz43 = a11*((a22*a34)-(a24*a32)) - a12*((a21*a34)-(a24*a31)) + a14*((a21*a32)-(a22*a31))

c43 = (-1)**(i+j)*matriz43
c43

0

Cálculo da célula a44
\begin{equation}
c_{44} = (-1)^{(4+4)}.
	\begin{bmatrix}
		a_{11} & a_{12}  & a_{13}  \\
		a_{21} & a_{22}  & a_{23}  \\
		a_{31} & a_{32}  & a_{33}  \nonumber \\ 
	\end{bmatrix} 
\end{equation}


In [20]:
i = 4
j = 4

matriz44 = a11*((a22*a33)-(a23*a32)) - a12*((a21*a33)-(a23*a31)) + a13*((a21*a32)-(a22*a31))

c44 = (-1)**(i+j)*matriz44
c44

-1

Agora vamos substituir os valores encontrados para cada cofator $c_{ij}$ na matriz $A$ para forma a matriz cofator $A_c$.


In [21]:
import numpy as np
Ac = np.array([[c11, c12, c13, c14],
               [c21, c22, c23, c24],
               [c31, c32, c33, c34],
               [c41, c42, c43, c44]
               ])
Ac

array([[-13,   5,   3,   2],
       [ -2,   1,   0,   0],
       [  0,   0,  -1,   0],
       [  5,  -2,   0,  -1]])

#### Cálculo da  Matriz transposta (AT).

Nós podemos calcular a matriz transposta fazendo a linha da matriz se transformar em coluna conforme abaixo.


In [22]:
# NA MATRIZ TRANSPOSTA AS LINHAS VIRA COLUNA
Matriz_T = [[c11, c21, c31, c41],
            [c12, c22, c32, c42],
            [c13, c23, c33, c43],
            [c14, c24, c34, c44]]
Matriz_T

[[-13, -2, 0, 5], [5, 1, 0, -2], [3, 0, -1, 0], [2, 0, 0, -1]]

Nós também podemos usar a biblioteca Numpy e resolver a transposta de uma matriz conforme mostrado abaixo.


In [23]:
# Mostrando os valores da transposta
AT =np.transpose(Ac)
AT

array([[-13,  -2,   0,   5],
       [  5,   1,   0,  -2],
       [  3,   0,  -1,   0],
       [  2,   0,   0,  -1]])

Nós já temos a matriz Transposta $A^T$, agora precisamos calcular o Determinante de uma matriz $4x4$ e substituir os resultados na Eq(2).

Vamos repetir a matriz $A$ com os valores numéricos abaixo:

\begin{equation}
	A = 
	\begin{bmatrix}
		a_{11} & a_{12}  & a_{13} & a_{14} \\
		a_{21} & a_{22}  & a_{23} & a_{24} \\
		a_{31} & a_{32}  & a_{33} & a_{34} \\
		a_{41} & a_{42}  & a_{43} & a_{44} \nonumber \\ 
	\end{bmatrix} 
    =
    \begin{bmatrix}
		4 & -1  & -1 & 0 \\
		-1 & 4  & 0 & -1 \\
		-1 & 0  & 4 & -1 \\
		0 & -1  & -1 & 4 \nonumber \\ 
	\end{bmatrix}
\end{equation}

O Determinante será encontrado fazendo:

$$ D = \sum a_{ij}A_{ij} $$

Ele poderá ser encontrado a partir de uma linha ou coluna. Vamos escolher a que apresenta muitos zeros porque qualquer número multiplicado por zero é igual a zero. Dessa forma o cálculo ficará mais fácil. Então vamos escolher a primeira linha para fazer o cálculo do Determinante.

$$  D = a_{11}A_{11} + a_{12}A_{12} + a_{13}A_{13} + a_{14}A_{14} $$

$$  D = 4A_{11} -1A_{12} -1A_{13} + 0A_{14} $$

Vamos usar a Eq(5) para calcular as matrizes $A_{ij}$ (repetido abaixo)

$$  A_c = (-1)^{(i+j)} [a_{ij}] ... Eq(5)$$ 

Já foi calculado acima: $A_{11}=c_{11}$, $A_{12}=c_{12}$ e $A_{13}=c_{13}$.


In [24]:
D = 4*c11 -1*c12 -1*c13 + 0*c14
D

-60

Substituindo os valores na Equação (1) para determinar a matriz inversa, ($A^{-1}$), temos:


In [27]:
A_inv = (1/D)*AT
A_inv

array([[ 0.21666667,  0.03333333, -0.        , -0.08333333],
       [-0.08333333, -0.01666667, -0.        ,  0.03333333],
       [-0.05      , -0.        ,  0.01666667, -0.        ],
       [-0.03333333, -0.        , -0.        ,  0.01666667]])