## <center>UNIVERSIDADE ESTADUAL DE SANTA CRUZ - UESC<center> <center>DEPARTAMENTO DE ENGENHARIAS E COMPUTAÇÃO - DEC </center>
#### <center>CURSO DE ENGENHARIA QUÍMICA</center>

**CET1012** - Modelagem, Simulação e Otimização de Processos Químicos.

**Tema**: Balanço em Reatores Químicos utilizando Cálculos Matriciais.

**Professor**: Prof. Dr E.R.Edwards

**Assunto**: Sistema de Reatores (Engenharia Química/Bioengenharia)

**Fonte**: Steven C. Chapra e Raymond P. Canale, "Métodos Numéricos para Engenharia", $7^a$ Edição. Editora: MacGraw Hill. página 283.


### Fundamentação.

A conservação de massa é uma das principais organizações na Engenharia Química. Ela contabiliza o balanço de massa que entra em um volume de controle pelo balanço de massa que sai do volume de controle. Caso haja reações químicas esses dados deverão ser contabilizados como acúmulo no reator.

$$Acumulo = Entrada - saída$$

Sendo assim, o balanço de massa representa um exercício de contabilidade para a substância específica que está sendo
modelada. Pelo próprio balanço, se as entradas forem maiores do que as saídas a massa da substância dentro do volume de
controle cresce. Se as saídas forem iguais as entradas o acúmulo é igual a zero e a massa permanece constante.



Para condições estáveis ou estacionárias o acúmulo será nulo e a equação torna-se.

$$entrada=saída$$


In [82]:
from IPython.display import display, HTML
display(HTML('<div style="text-align:center;"><img src="acumulacao.png" width="400"><br>Figura 1: Exemplo de balanço.</div>'))


Podemos usar a conservação da massa para determinar as concentrações estacionárias de um sistema de reatores.

Podemos usar a conservação da massa para determinar as concentrações estacionárias de um sistema de reatores.

In [83]:
from IPython.display import display, HTML
display(HTML('<div style="text-align:center;"><img src="reator1.png" width="600"><br>Figura 2: Exemplo reator, balanço de massa.</div>'))


$$Q_1.c_1 + Q_2.c_2 =  Q_3.c_3$$

$$ c_3 = \frac{Q_1.c_1 + Q_2.c_2}{Q_3}$$


In [84]:
# DECLARANDO AS VARIAVEIS

# Dados das vazões 
Q1, Q2, Q3 = 2.0, 1.5, 3.5

# Dados das concentrações
c1, c2 = 25, 10

In [85]:
c3 =(((Q1*c1)+(Q2*c2))/Q3)

def line():
    print("-"*45)

line()
print("O valor da concentração c3 é: {:.2f}".format(c3), "mg/m3")
line()

---------------------------------------------
O valor da concentração c3 é: 18.57 mg/m3
---------------------------------------------


#### Aplicação industrial - Caso 1.

Este tipo de cálculo é de grande utilidade para Engenharia Química e Petroquímica em que deve ser projetado um reator contendo misturas com concentrações específicas. Nesse exercício foi usado **álgebra** para determinar a concentração de um único reator usando o conhecimento de balanços de massa visto em assuntos anteriores. Dessa forma, fica mais fácil a utilização de computador para a realização desse tipo de cálculo.


In [86]:
from IPython.display import display, HTML
display(HTML('<div style="text-align:center;"><img src="reator2.png" width="600"><br>Figura 3: Exemplo reator, balanço de massa.</div>'))


#### Informações:
PASSOS:
1. Estabelecer um volume de controle em cada reator.
2. Faça um balanço de massa em cada reator (entrada de fluxo positivo, saída de fluxo negativo).
3. Serão 5 equações e 5 incógitas ($c_1$, $c_2$, $c_3$, $c_4$, $c_5$)
4. Monte a Matriz: $Ax=b$
6. Cálcule a matriz inversa $A$.
7. Cálcule a incógnita $x$ - coloque os valores de saída separados ($c_1$, $c_2$, $c_3$, $c_4$, $c_5$)<br>
$c_1 = x[0,0]$ <br>
$c_2 = x[1,0]$ <br>
$c_3 = x[2,0]$ <br>
$c_4 = x[3,0]$ <br>
$c_5 = x[4,0]$ <br>
8. Confira seus cálculos substituindo os valores nas equações.


#### Solução:

#### Primeiro Reator:

In [87]:
from IPython.display import display, HTML
display(HTML('<div style="text-align:center;"><img src="reator3.png" width="600"><br>Figura 4: Calculo do reator 1.</div>'))


BALANÇO DE MASSA NO PRIMEIRO REATOR

In [88]:
from IPython.display import display, HTML
display(HTML('<div style="text-align:center;"><img src="image1.png" width="600"><br>Figura 4: Calculo do reator 1.</div>'))


In [89]:
# PARA FAZER OS CALCULOS É PRECISO VERIFICAR OS VALORES QUE ENTRA E QUE SAI.

q01, q31, q15, q12 = 5, 1, 3, 3
c01 = 10

#### Segundo Reator:

BALANÇO DE MASSA NO SEGUNDO REATOR

In [90]:
from IPython.display import display, HTML
display(HTML('<div style="text-align:center;"><img src="reator4.png" width="600"><br>Figura 5: Calculo do reator 2.</div>'))

In [91]:
from IPython.display import display, HTML
display(HTML('<div style="text-align:center;"><img src="image2.png" width="600"><br></div>'))


#### Terceiro Reator:

BALANÇO DE MASSA NO TERCEIRO REATOR

In [92]:
from IPython.display import display, HTML
display(HTML('<div style="text-align:center;"><img src="reator5.png" width="600"><br>Figura 6: Calculo do reator 3.</div>'))

In [93]:
from IPython.display import display, HTML
display(HTML('<div style="text-align:center;"><img src="image3.png" width="600"><br></div>'))


#### Quarto Reator:

BALANÇO DE MASSA NO QUARTO REATOR

In [94]:
from IPython.display import display, HTML
display(HTML('<div style="text-align:center;"><img src="reator6.png" width="600"><br>Figura 7: Calculo do reator 4.</div>'))

In [95]:
from IPython.display import display, HTML
display(HTML('<div style="text-align:center;"><img src="image4.png" width="600"><br></div>'))


#### Quinto Reator:

BALANÇO DE MASSA NO QUINTO REATOR

In [96]:
from IPython.display import display, HTML
display(HTML('<div style="text-align:center;"><img src="reator7.png" width="600"><br>Figura 8: Calculo do reator 5.</div>'))

In [97]:
from IPython.display import display, HTML
display(HTML('<div style="text-align:center;"><img src="image5.png" width="600"><br></div>'))


Todas equações dos cinco reatores.

In [98]:
from IPython.display import display, HTML
display(HTML('<div style="text-align:center;"><img src="image6.png" width="350"><br></div>'))


In [99]:
from IPython.display import display, HTML
display(HTML('<div style="text-align:center;"><img src="tabela1.png" width="600"><br></div>'))


In [100]:
from IPython.display import display, HTML
display(HTML('<div style="text-align:center;"><img src="matriz.png" width="600"><br></div>'))


A matriz A tem a forma de uma matriz 5x5, precisamos encontrar um modelo que possamos utilizar para resolução dessa matriz. Vamos usar o modelo de matrizes __cst_matrix__ para isso, precisamos criar uma matriz com: linhas, colunas e dados (row, col, data).

In [101]:
import numpy as np
from scipy import sparse
from scipy.sparse import csr_matrix

In [102]:
# DECLARANDO AS ARRAYS.

row = np.array([0, 0, 1, 1, 2, 2, 3, 3, 3, 3, 4, 4, 4])
col = np.array([0, 2, 0, 1, 1, 2, 1, 2, 3, 4, 0, 1, 4])
data = np.array([6, -1, 3, -3, -1, 9, 1, 8, -11, 2, 3, 1, -4])


In [103]:
A_coord = sparse.coo_matrix((data, (row, col)), dtype=float)
print(A_coord)

  (0, 0)	6.0
  (0, 2)	-1.0
  (1, 0)	3.0
  (1, 1)	-3.0
  (2, 1)	-1.0
  (2, 2)	9.0
  (3, 1)	1.0
  (3, 2)	8.0
  (3, 3)	-11.0
  (3, 4)	2.0
  (4, 0)	3.0
  (4, 1)	1.0
  (4, 4)	-4.0


Podemos transformar a matriz coordenada (COO) para matriz esparsa usando: .toarray()

In [104]:
A = sparse.coo_matrix((data, (row, col)), dtype=float).toarray()
print(A)

[[  6.   0.  -1.   0.   0.]
 [  3.  -3.   0.   0.   0.]
 [  0.  -1.   9.   0.   0.]
 [  0.   1.   8. -11.   2.]
 [  3.   1.   0.   0.  -4.]]


### PARA A PROVA INICIA OS CÁLCULOS AQUI:

In [105]:
A = sparse.csr_matrix((data, (row, col)), shape=(5,5), dtype=float).toarray()
A

array([[  6.,   0.,  -1.,   0.,   0.],
       [  3.,  -3.,   0.,   0.,   0.],
       [  0.,  -1.,   9.,   0.,   0.],
       [  0.,   1.,   8., -11.,   2.],
       [  3.,   1.,   0.,   0.,  -4.]])

In [106]:
# CALCULANDO A INVERSA DA MATRIZ

A_inv = np.linalg.inv(A)


In [107]:
# DECLARANDO OS VALORES DO VETOR B

b1, b2, b3, b4, b5 = 50, 0, 160, 0, 0

b = np.array([b1, b2, b3, b4, b5])
print(b)

[ 50   0 160   0   0]


In [108]:
# CALCULO DAS ICOGNITAS

x = A_inv.dot(b)
x

array([11.50943396, 11.50943396, 19.05660377, 16.99828473, 11.50943396])

In [109]:
c1 = x[0]
c2 = x[1]
c3 = x[2]
c4 = x[3]
c5 = x[4]

In [110]:
def line():
    print("-"*45)

line()
print( 'RESULTADOS DAS CONCENTRAÇÕES' )
line()
print("O valor da concentração c1 é: {:.2f}".format(c1), "mg/m3")
print("O valor da concentração c2 é: {:.2f}".format(c2), "mg/m3")
print("O valor da concentração c3 é: {:.2f}".format(c3), "mg/m3")
print("O valor da concentração c4 é: {:.2f}".format(c4), "mg/m3")
print("O valor da concentração c5 é: {:.2f}".format(c5), "mg/m3")
line()

---------------------------------------------
RESULTADOS DAS CONCENTRAÇÕES
---------------------------------------------
O valor da concentração c1 é: 11.51 mg/m3
O valor da concentração c2 é: 11.51 mg/m3
O valor da concentração c3 é: 19.06 mg/m3
O valor da concentração c4 é: 17.00 mg/m3
O valor da concentração c5 é: 11.51 mg/m3
---------------------------------------------


CINFERINDO OS RESULTADOS

In [111]:
z1 = 6*c1-c3
z3 = -c2 +9*c3

In [112]:
line()
print( 'CONFERINDO OS RESULTADOS DAS CONCENTRAÇÕES' )
line()
print(f"O resultado de b1={b1} e z1 = {z1:.1f}", "mg/m3")
print(f"O resultado de b3={b3} e z3 = {z3:.1f}", "mg/m3")
line()

---------------------------------------------
CONFERINDO OS RESULTADOS DAS CONCENTRAÇÕES
---------------------------------------------
O resultado de b1=50 e z1 = 50.0 mg/m3
O resultado de b3=160 e z3 = 160.0 mg/m3
---------------------------------------------
