### __PROVA 3__

In [1]:
import numpy as np
from scipy import sparse
from scipy.sparse import csr_matrix

In [2]:
# DECLARANDO AS VARIAVEIS

row = np.array([0, 0, 1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4])
col = np.array([0, 1, 0, 1, 2, 1, 2, 3, 2, 3, 4, 3, 4])
data = np.array([8, -4, 8, -10, 2, 6, -11, 5, 3, -7, 4, -2, 4])

In [3]:
A = sparse.csr_matrix((data, (row, col)), shape=(5,5), dtype=float).toarray()
A

array([[  8.,  -4.,   0.,   0.,   0.],
       [  8., -10.,   2.,   0.,   0.],
       [  0.,   6., -11.,   5.,   0.],
       [  0.,   0.,   3.,  -7.,   4.],
       [  0.,   0.,   0.,  -2.,   4.]])

In [4]:
# CALCULANDO A INVERSA DA MATRIZ

A_inv = np.linalg.inv(A)

In [5]:
# DECLARANDO OS VALORES DO VETOR B

b1, b2, b3, b4, b5 = 80, 0, 0, 0, 30

b = np.array([b1, b2, b3, b4, b5])
print(b)

[80  0  0  0 30]


In [6]:
# CALCULO DAS ICOGNITAS

x = A_inv.dot(b)
x

array([19.72222222, 19.44444444, 18.33333333, 17.        , 16.        ])

In [7]:
c1 = x[0]
c2 = x[1]
c3 = x[2]
c4 = x[3]
c5 = x[4]

In [8]:
def line():
    print("-"*45)

line()
print( 'RESULTADOS DAS CONCENTRAÇÕES' )
line()
print("O valor da concentração c1 é: {:.2f}".format(c1), "mg/m3")
print("O valor da concentração c2 é: {:.2f}".format(c2), "mg/m3")
print("O valor da concentração c3 é: {:.2f}".format(c3), "mg/m3")
print("O valor da concentração c4 é: {:.2f}".format(c4), "mg/m3")
print("O valor da concentração c5 é: {:.2f}".format(c5), "mg/m3")
line()

---------------------------------------------
RESULTADOS DAS CONCENTRAÇÕES
---------------------------------------------
O valor da concentração c1 é: 19.72 mg/m3
O valor da concentração c2 é: 19.44 mg/m3
O valor da concentração c3 é: 18.33 mg/m3
O valor da concentração c4 é: 17.00 mg/m3
O valor da concentração c5 é: 16.00 mg/m3
---------------------------------------------


CONFERINDO OS RESULTADOS

In [9]:
z1 = 8*c1-4*c2
z5 = 4*c5 - 2*c4

In [10]:
line()
print( 'CONFERINDO OS RESULTADOS DAS CONCENTRAÇÕES' )
line()
print(f"O resultado de b1={b1} e z1 = {z1:.2f}", "mg/m3")
print(f"O resultado de b5={b5} e z5 = {z5:.2f}", "mg/m3")
line()

---------------------------------------------
CONFERINDO OS RESULTADOS DAS CONCENTRAÇÕES
---------------------------------------------
O resultado de b1=80 e z1 = 80.00 mg/m3
O resultado de b5=30 e z5 = 30.00 mg/m3
---------------------------------------------
